const userMaker = {
  users: [
    { email: "KCouture@email.com", username: "Babyteerpl" },
    { email: "LWaldrup@email.com", username: "BauerRomance" },
    { email: "PMaciel@email.com", username: "Bauersize" },
    { email: "JCardona@email.com", username: "CampyGigaAni" },
    { email: "MBillingsley@email.com", username: "CapoBlabMedium" },
    { email: "JAnguiano@email.com", username: "ClawMonster" },
    { email: "LSenn@email.com", username: "Daniumtr" },
    { email: "KCamacho@email.com", username: "Delpoide" },
    { email: "EHermsen@email.com", username: "DressyNinja" },
    { email: "DLoh@email.com", username: "Endacker" },
    { email: "APeople@email.com", username: "HempSee" },
    { email: "PStogsdill@email.com", username: "Hipperme" },
    { email: "JMarinez@email.com", username: "Horapper" },
    { email: "DFretz@email.com", username: "Kenjimletta" },
    { email: "CBrandis@email.com", username: "Latestodex" },
    { email: "NConerly@email.com", username: "Leaketaidn" },
    { email: "JGanz@email.com", username: "Maxusan" },
    { email: "AEtheredge@email.com", username: "Natheiosen" },
    { email: "FLederer@email.com", username: "Olathwai" },
    { email: "DButler@email.com", username: "Portity" },
    { email: "TRepka@email.com", username: "Raynawashbe" },
    { email: "NWalkes@email.com", username: "Screelash" },
    { email: "MKyer@email.com", username: "Slicessus" },
    { email: "GTustin@email.com", username: "TagzNetwork" },
    { email: "CSmallwood@email.com", username: "TinnyFinest" },
    { email: "LLy@email.com", username: "TrainTrippin" },
    { email: "TAdolphson@email.com", username: "TwitterAlly" },
    { email: "SKellog@email.com", username: "Unitrimek" },
    { email: "TJoyner@email.com", username: "VikingBurke" },
    { email: "ECamire@email.com", username: "Xantronskel" },
    { email: "DTittle@email.com", username: "ArticlesSheer" },
    { email: "CLape@email.com", username: "Axonikab" },
    { email: "AHarpe@email.com", username: "BluePhobicLuc" },
    { email: "NCygan@email.com", username: "Bunnytamayt" },
    { email: "AStrahl@email.com", username: "Casuallson" },
    { email: "OSuther@email.com", username: "Czariagent" },
    { email: "EHoffmann@email.com", username: "DiaryKai" },
    { email: "JArmes@email.com", username: "Drummeris" },
    { email: "SDreiling@email.com", username: "Flirtypyra" },
    { email: "WRossman@email.com", username: "Ganagene" },
    { email: "RHutt@email.com", username: "Haventai" },
    { email: "KMackinnon@email.com", username: "Information" },
    { email: "DMick@email.com", username: "Invaderalle" },
    { email: "AGallogly@email.com", username: "LabsCuddly" },
    { email: "HShumake@email.com", username: "Lawmark" },
    { email: "BKmetz@email.com", username: "MaddVivalaXcaptain" },
    { email: "LWaterbury@email.com", username: "Mediasignov" },
    { email: "RKoss@email.com", username: "PatPopular" },
    { email: "MMaloy@email.com", username: "ProBornAlert" },
    { email: "BMoorhead@email.com", username: "Proxius" }
  ]
};

module.exports = userMaker;
